import { existsSync, readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { resolve } from 'node:path';

// All six plugins are compiled even in an unconfigured APK; no reflection/stubs.
export function configureChinaPush(client, app) {
  const source =
    process.env.JPUSH_ANDROID_CONFIG ||
    (existsSync('config/jpush-android.json')
      ? readFileSync('config/jpush-android.json', 'utf8')
      : '{}');
  const config = JSON.parse(source);
  const allowed = ['appKey', 'huawei', 'honor', 'xiaomi', 'oppo', 'vivo', 'meizu'];
  if (
    !config ||
    typeof config !== 'object' ||
    Array.isArray(config) ||
    Object.keys(config).some((k) => !allowed.includes(k))
  )
    throw new Error('JPUSH_ANDROID_CONFIG 字段错误；不要把 MasterSecret 放入 APK 配置');
  const fields = {
    honor: ['appId'],
    xiaomi: ['appId', 'appKey'],
    oppo: ['appId', 'appKey', 'appSecret'],
    vivo: ['appId', 'appKey'],
    meizu: ['appId', 'appKey'],
  };
  for (const [vendor, keys] of Object.entries(fields)) {
    const value = config[vendor];
    if (!value) continue;
    if (
      typeof value !== 'object' ||
      Array.isArray(value) ||
      Object.keys(value).some((k) => !keys.includes(k)) ||
      keys.some((k) => !value[k])
    )
      throw new Error(`${vendor} 客户端配置不完整`);
    for (const v of Object.values(value))
      if (typeof v !== 'string' || !/^[a-zA-Z0-9._-]+$/.test(v))
        throw new Error(`${vendor} 凭据格式错误`);
  }
  if (config.appKey && !/^[a-fA-F0-9]{24}$/.test(config.appKey))
    throw new Error('JPush AppKey 必须为 24 位十六进制字符');
  if (config.huawei !== undefined && config.huawei !== true)
    throw new Error('huawei 应设置为 true，具体配置来自 AGCONNECT_SERVICES_JSON');
  if (Object.keys(config).some((k) => k !== 'appKey') && !config.appKey)
    throw new Error('厂商配置需要 JPush AppKey');
  const agconnect = resolve(app, 'agconnect-services.json');
  if (process.env.AGCONNECT_SERVICES_JSON)
    writeFileSync(agconnect, process.env.AGCONNECT_SERVICES_JSON);
  else if (existsSync('config/agconnect-services.json'))
    copyFileSync('config/agconnect-services.json', agconnect);
  if (config.huawei && !existsSync(agconnect))
    throw new Error('启用华为通道必须提供 AGCONNECT_SERVICES_JSON');
  const configured = Boolean(config.appKey);
  const prefixed = (value, prefix) =>
    value ? (value.startsWith(prefix) ? value : prefix + value) : '';
  const placeholders = {
    JPUSH_APPKEY: config.appKey || '000000000000000000000000',
    JPUSH_CHANNEL: 'love-android',
    HONOR_APPID: config.honor?.appId || '',
    XIAOMI_APPID: config.xiaomi?.appId || '',
    XIAOMI_APPKEY: config.xiaomi?.appKey || '',
    OPPO_APPID: prefixed(config.oppo?.appId, 'OP-'),
    OPPO_APPKEY: prefixed(config.oppo?.appKey, 'OP-'),
    OPPO_APPSECRET: prefixed(config.oppo?.appSecret, 'OP-'),
    VIVO_APPID: config.vivo?.appId || '',
    VIVO_APPKEY: config.vivo?.appKey || '',
    MEIZU_APPID: prefixed(config.meizu?.appId, 'MZ-'),
    MEIZU_APPKEY: prefixed(config.meizu?.appKey, 'MZ-'),
  };
  const gradle = `// Generated by scripts/android-push.mjs. Credentials are client SDK parameters only.
android {
  defaultConfig {
    manifestPlaceholders += [${Object.entries(placeholders)
      .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
      .join(', ')}]
  }
}
configurations.configureEach {
  resolutionStrategy.force 'cn.jiguang.sdk:jcore:5.5.0'
}
dependencies {
  implementation 'cn.jiguang.sdk:jpush:6.2.0'
  ${['huawei', 'honor', 'xiaomi', 'oppo', 'vivo', 'meizu'].map((v) => `implementation 'cn.jiguang.sdk.plugin:${v}:6.2.0'`).join('\n  ')}
}
${config.huawei ? "apply plugin: 'com.huawei.agconnect'" : ''}
`;
  writeFileSync(resolve(app, 'love-push.gradle'), gradle);
  const appGradle = resolve(app, 'build.gradle');
  let text = readFileSync(appGradle, 'utf8');
  if (!text.includes("apply from: 'love-push.gradle'"))
    text += "\napply from: 'love-push.gradle'\n";
  writeFileSync(appGradle, text);
  const rootGradle = resolve(client, 'android/build.gradle');
  text = readFileSync(rootGradle, 'utf8');
  if (!text.includes('https://developer.huawei.com/repo/'))
    text = text.replaceAll(
      'mavenCentral()',
      "mavenCentral()\n        maven { url 'https://developer.huawei.com/repo/' }",
    );
  if (config.huawei && !text.includes('com.huawei.agconnect:agcp'))
    text = text.replace(
      'dependencies {',
      "dependencies {\n        classpath 'com.huawei.agconnect:agcp:1.9.1.301'",
    );
  writeFileSync(rootGradle, text);
  const javaDir = resolve(app, 'src/main/java/com/kevinhuang/love');
  mkdirSync(javaDir, { recursive: true });
  for (const name of [
    'MainActivity',
    'ChinaPushPlugin',
    'LovePushReceiver',
    'PushClickActivity',
    'LovePushService',
  ])
    copyFileSync(resolve(client, 'native', name + '.java'), resolve(javaDir, name + '.java'));
  const values = resolve(app, 'src/main/res/values');
  mkdirSync(values, { recursive: true });
  writeFileSync(
    resolve(values, 'love_push.xml'),
    `<resources><bool name="china_push_configured">${configured}</bool></resources>`,
  );
  const manifestPath = resolve(app, 'src/main/AndroidManifest.xml');
  text = readFileSync(manifestPath, 'utf8');
  if (!text.includes('xmlns:tools='))
    text = text.replace('<manifest ', '<manifest xmlns:tools="http://schemas.android.com/tools" ');
  if (!text.includes('.LovePushReceiver')) {
    text = text.replace(
      '</application>',
      `<receiver android:name=".LovePushReceiver" android:exported="false"><intent-filter><action android:name="cn.jpush.android.intent.RECEIVE_MESSAGE"/><category android:name="com.kevinhuang.love"/></intent-filter></receiver>
    <service android:name=".LovePushService" android:process=":pushcore" android:exported="false"><intent-filter><action android:name="cn.jiguang.user.service.action"/></intent-filter></service>
    <activity android:name=".PushClickActivity" android:exported="true" android:theme="@android:style/Theme.NoDisplay"><intent-filter><action android:name="com.kevinhuang.love.OPEN_CHAT"/><category android:name="android.intent.category.DEFAULT"/></intent-filter></activity>
    <meta-data android:name="push_kit_auto_init_enabled" android:value="false" tools:replace="android:value"/>
    </application>`,
    );
    for (const permission of [
      'ACCESS_COARSE_LOCATION',
      'ACCESS_FINE_LOCATION',
      'ACCESS_BACKGROUND_LOCATION',
      'READ_PHONE_STATE',
      'QUERY_ALL_PACKAGES',
      'WRITE_EXTERNAL_STORAGE',
      'READ_EXTERNAL_STORAGE',
    ])
      text = text.replace(
        '</manifest>',
        `<uses-permission android:name="android.permission.${permission}" tools:node="remove"/></manifest>`,
      );
  }
  writeFileSync(manifestPath, text);
  return {
    jpushConfigured: configured,
    vendors: Object.keys(config).filter((k) => k !== 'appKey'),
  };
}
